### ISSUE TITLE
Add Python 3.6 support 

### ISSUE THREAD

**Issue by singulared** [rambler-digital-solutions/aioriak#23]
Now i think problem in riak==2.5.5 module. We should check updates for official riak module/

**Comment by singulared** [comment]
```python
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules'
  File "/opt/python/3.6.0/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/3.6.0/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/python/3.6.0/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/command/develop.py", line 36, in run
    self.install_for_development()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/command/develop.py", line 137, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 747, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 846, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1118, in best_match
    return self.obtain(req, installer)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1130, in obtain
    return installer(requirement)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 700, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
    run_setup(setup_script, args)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/sandbox.py", line 258, in run_setup
    raise
  File "/opt/python/3.6.0/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/opt/python/3.6.0/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-jk2mv1gv/riak-2.5.5/setup.py", line 8, in <module>
    description='Async implementation of Riak DB python client',
ImportError: cannot import name 'setup_timeseries'
```

**Comment by singulared** [comment]
Need remove python3-riak-pb package and move to https://github.com/basho/riak_pb repository

**Comment by singulared** [comment]
Updated riak client to 2.7.0 in 78931e155fd41c34d2dc391a3bc931b4b9e50cfd
